Improvment/refine data processing
zeitspace/stressmodel pull request #19
Opened 2022-08-09 18:43 UTC by catalinzpop

The json file is not yet hooked up properly to the model.js file. It first needs proofreading because of human error. Most of the attribute sections are evident which section they transcribe except for the last two. "bike_lane_no_parking" uses the "<=6 Foot (1.8 metre) Bike Lane,  no parking on the street" section. "bike_lane_with_parking" uses the "<4.5 metre bike lane reach with parking on the street" section. The other two sections from the excel file are not used since we cannot calculate lane width or separation distance.

2022-08-09 18:45 UTC, catalinzpop commented
![](https://github.trello.services/images/mini-trello-icon.png) [Refine data processing/filtering based on David's investigation](https://trello.com/c/GghEOZpK/217-refine-data-processing-filtering-based-on-davids-investigation)

2022-08-10 20:03 UTC, brentlintner approved these changes
This passes the original schema aside from newly added properties.

I've also rubber ducked through it to see if I saw anything but LGTM!

2022-08-11 20:37 UTC, catalinzpop commented
This PR now works with the new model and it should run and insert data into db the same way as before

2022-08-11 21:50 UTC, brentlintner approved these changes
I plan to try this out with the router myself, but since it takes ~30min, in the meantime:

LGTM! 🦘

2022-08-11 21:50 UTC, brentlintner commented on ltsanalyzer.js
>      let data = { '-1': [], 0: [], 1: [], 2: [], 3: [], 4: [], none: []}
microscopic nit: could be ideal to have a DRY method for `data`. 🤷

2022-08-11 21:50 UTC, brentlintner commented on model.js
> +import * as modelinfo from './stressmodel_v1p4.json' assert {type: 'json'};
suggestion: assuming this will be renamed to `stressmodel.json` when fully ready? 😄

2022-08-11 21:50 UTC, brentlintner commented on model.js
> +    const issh = isSelectedServiceHighway(way, model.highway_service);
nit for a rainy day, since this is original fork code:

var names could be more descriptive, or at least, reading below, once you move away from the assignment, things like `bp.result` lose meaning.

maybe a destructing assignment can help here.. or perhaps better yet, consider changing the name & signature to reflect the dual concern the method has, i.e like `getMaxSpeed`:

```javascript
const selectedServiceHighwayResult = FindSelectedServiceHighway(way, model.highway_service)

...

} else if (selectedServiceHighwayResult) {
```

2022-08-11 21:50 UTC, brentlintner commented on model.js
> +  return isBikingPermitted(way, model.biking_not_permitted).permitted;
Same here with the nit for a rainy day. To read it literally, it reads like:

```javascript
QUESTION(ARG1, ARG2).QUESTION
```

2022-08-11 21:50 UTC, brentlintner commented on model.js
> +      result = { isSelectedServiceHighway: true, result: { lts: i.lts, message: i.message, rule: i.rule } };
we should refactor these methods one day into a single method. There has to be like 90% similarity them. 🤔 😄

2022-08-11 21:50 UTC, brentlintner commented on model.js
> +      result = { isSelectedServiceHighway: true, result: { lts: i.lts, message: i.message, rule: i.rule } };
Ok so it's 80-85% actually lol:

[matches.txt](https://github.com/zeitspace/stressmodel/files/9312274/matches.txt)

2022-08-16 18:21 UTC, catalinzpop commented on model.js
> +import * as modelinfo from './stressmodel_v1p4.json' assert {type: 'json'};
Yes that will be the case. I will change it before we push it

2022-08-16 18:24 UTC, catalinzpop commented on model.js
> +      result = { isSelectedServiceHighway: true, result: { lts: i.lts, message: i.message, rule: i.rule } };
Yeah I agree actually but I wanted to do it in a separate ticket so that any weird behaviour happening on this branch should be only caused by the new data and not the new model functions

2022-08-18 18:57 UTC, peterspenler requested changes
A bit of a nit but there is inconsistent casing on LTS in rationale messages (sometimes its "LTS" other times its "lts")

2022-08-18 18:57 UTC, peterspenler commented on stressmodel.json
> +        "message": "Assigned lts 1 since highway=footway and bicycle=designated, yes and footway!=crossing tag.",
"and footway!=crossing tag" doesn't read clearly, I think something like "and doesn't have footway=crossing tag" would be clearer.

2022-08-18 18:57 UTC, peterspenler commented on stressmodel.json
> +            "present": false
The rule message says that the `bicycle=designated` tag is present but there is no attribute to check for that tag

2022-08-18 18:57 UTC, peterspenler commented on stressmodel.json
> +        "message": "Assigned lts 1 since highway=construction and construction=path, footway, cycleway tag.",
"and construction=path, footway, cycleway tag." reads confusingly, I'd say something like " and construction tag is path, footway, or cycleway"

2022-08-18 18:57 UTC, peterspenler commented on stressmodel.json
>        {
This assignment has the same stress level as the previous so I think having another rule for it is redundant when we could just mark every residential road with a speed at or above 70 as a level 4 with one rule

2022-08-18 18:57 UTC, peterspenler commented on stressmodel.json
> +  "bike_lane_no_parking": {
I think the messages for these assignments could specify that there is a bike lane present.

2022-08-18 18:57 UTC, peterspenler commented on stressmodel.json
> +        "message": "Setting LTS to 2 because parking present, maxspeed is below 50km/h, and highway=residential, living_street.",
This message should specify that the highway tag could be tertiary, service, minor, unclassified, track as well

2022-08-18 18:57 UTC, peterspenler commented on stressmodel.json
> +        "message": "Setting LTS to 3 because parking present, maxspeed is between 50km/h and 60km/h, and highway=residential, living_street.",
This message should specify that the highway tag could be tertiary, service, minor, unclassified, track as well

2022-08-18 18:57 UTC, peterspenler commented on stressmodel.json
> +        "message": "Setting LTS to 4 because parking present, maxspeed is greater 60km/h, and highway=residential, living_street.",
This message should specify that the highway tag could be tertiary, service, minor, unclassified, track as well

2022-08-18 18:57 UTC, peterspenler commented on stressmodel.json
> +  "bike_lane_with_parking": {
Again I think the messages here could specify that a bike lane is present

2022-08-18 18:57 UTC, peterspenler commented on stressmodel.json
> +        "message": "No maxspeed tag. Using default value of 40km/h when highway=service and service=parking_isle, driveway, alley."
parking_aisle is misspelled

2022-08-18 18:59 UTC, peterspenler commented on stressmodel_v1p4.json
> +  "is_mixed_traffic": {
Accidentally left this comment on the old stressmodel.json, but it still applies to the current stressmodel.json

2022-08-18 19:13 UTC, catalinzpop commented on stressmodel.json
> +        "message": "No maxspeed tag. Using default value of 40km/h when highway=service and service=parking_isle, driveway, alley."
Thank you!

2022-08-18 20:14 UTC, peterspenler commented on stressmodel.json
> +      {
This assignment should be removed. The `cycleway=separate` tag is used to indicate that a cycleway associated with that road is entered into the osm data as a separate entity. Thus we should be routing on that entity instead of the associated road otherwise the user might mistakenly think that the app intends for them to use the road itself. 

This issue can be seen where the Conestoga Parkway meets King street in Waterloo. There, King Street has the tag  `cycleway=separate` referring to a independent cycleway adjacent to the street. However, this rule then means that that segment of King Street will get a stress level of 1 which is not appropriate for that strech of road since it should be the independent cycleway that should get that stress level.

2022-08-18 20:52 UTC, catalinzpop commented on stressmodel.json
> +      {
Good catch I will get rid of it

2022-08-18 21:58 UTC, catalinzpop commented on stressmodel_v1p4.json
> +  "is_mixed_traffic": {
There is a problem with adding the surface not equal to asphalt or paved since majority of ways do not have that tag at all. This causes almost all level 3 drop down to level 2 because of this. The count looks something like this: 
          NULL = 0, 
            -1 = 10063, 
             0 = 15934, 
             1 = 13905, 
             2 = 43632, 
             3 = 223, 
             4 = 4842
instead of:
          NULL = 0, 
            -1 = 10063, 
             0 = 15934, 
             1 = 13905, 
             2 = 31642, 
             3 = 12080, 
             4 = 4975.
So I opted to not include this set of assessments.

2022-08-19 14:32 UTC, peterspenler requested changes

2022-08-19 14:32 UTC, peterspenler commented on stressmodel.json
> +            "present": false
This assignment should have the `bicycle=designated` attribute otherwise we will give all footways including sidewalks a stress level of 1 causing the router to frequently send the user along sidewalks which are illegal to cycle on.

2022-08-19 14:32 UTC, peterspenler commented on stressmodel.json
> +        "message": "Assigned lts 1 since highway=construction and construction tag is has a path, footway, or cycleway value.",
"is has a" isn't grammatically correct, should be "has a"

2022-08-19 14:32 UTC, peterspenler commented on stressmodel.json
> +        "message": "Setting LTS to 1 because blike lane with no parking present, maxspeed is below 60km/h, and highway=residential, living_street.",
All the messages in this section say "blike lane" instead of "bike lane"

2022-08-19 14:32 UTC, peterspenler commented on stressmodel.json
> +        "message": "Setting LTS to 2 because blike lane with parking present, maxspeed is below 50km/h, and highway=residential, living_street, tertiary, service, minor, unclassified, tertiary_link."
All the messages in this section also say "blike lane" instead of "bike lane"

2022-08-19 15:37 UTC, catalinzpop commented on stressmodel.json
> +            "present": false
I had it here as bicycle=designated but that was my solution because it wasn't being caught in the "biking_not_permitted" section which comes before this one, and that was a bug. Theres an assignment looks for footway=sidewalk and bicycle!=yes or designated that was not working before. With that assignment it should catch those cases before it reaches this section

2022-08-19 20:01 UTC, peterspenler approved these changes
LGTM

2022-08-19 20:48 UTC, merged