Improvement/tweak new model data to remove strange behaviour
zeitspace/stressmodel pull request #25
Opened 2022-08-26 17:53 UTC by catalinzpop

2022-08-26 20:59 UTC, brentlintner approved these changes
LGTM! ~~As I mentioned to Catalin, I'm going to build and exploratory test this when manually pushing to Experimental.~~

2022-08-27 17:09 UTC, brentlintner commented
@catalinzpop I forgot to mention, I looked at the merge conflicts and forced pushed the branch with changes that don't conflict.

In the end I think @peterspenler's PR changed a few of the same things:

https://github.com/zeitspace/stressmodel/commit/e22f605dc7260a914e43e7983aab8209c2746b86

Going to leave this for @peterspenler to review though in case he fixed a similar thing? 🤷 😄

2022-09-01 21:08 UTC, peterspenler requested changes

2022-09-01 21:08 UTC, peterspenler commented on stressmodel.json
> +        "lts": 1
This case should already be caught by rule s6 above

2022-09-09 20:32 UTC, peterspenler requested changes

2022-09-09 20:32 UTC, peterspenler commented on stressmodel.json
> +            "values": null,
`values` doesn't need to be set to null, it can just be excluded.

Also the message for this rule says that "highway=footway" when it should say that "footway tag is present". It should also specify that the footway is not a crossing.

2022-09-16 15:51 UTC, closed without merging