Added the ability to push directly to db
zeitspace/stressmodel pull request #3
Opened 2022-04-18 15:22 UTC by catalinzpop

2022-04-18 15:33 UTC, catalinzpop commented
![](https://github.trello.services/images/mini-trello-icon.png) [Reimplement search/algorithm for preparing stress level data](https://trello.com/c/f5oSsJGo/87-reimplement-search-algorithm-for-preparing-stress-level-data)

2022-04-18 20:18 UTC, peterspenler requested changes

2022-04-18 22:44 UTC, catalinzpop commented on ltsanalyzer.js
> +      data[this.ways[id].level].push(id)
I'm not sure why it's failing but that level attribute being set as an attribute by the algorithm in the processWays function here:
<img width="739" alt="Screen Shot 2022-04-18 at 6 42 33 PM" src="https://user-images.githubusercontent.com/87994296/163888867-5fbbbcd0-e578-4491-9967-58807fda8c1a.png">
That data object is used only as an arg to pass down to the sequelize function:
<img width="935" alt="Screen Shot 2022-04-18 at 6 39 54 PM" src="https://user-images.githubusercontent.com/87994296/163888982-dca40ca7-903d-4e27-a031-2e5443ea3496.png">

2022-04-18 22:45 UTC, catalinzpop commented on ltsanalyzer.js
> +      data[this.ways[id].level].push(id)
I will definitely add the 'stress_level' attribute name in the .env for sure so it can be named

2022-04-19 15:50 UTC, brentlintner approved these changes
Epicness. 💪

2022-04-19 15:50 UTC, brentlintner commented on README.md
> + This will do the same thing as the above example except it will not create json files but will instead update the stress_level collumn in the ways table of your postgress routing database. This opti
spl: column?

2022-04-19 15:50 UTC, brentlintner commented on README.md
> +
🚀

2022-04-19 15:50 UTC, brentlintner commented on loadmodel.js
> -'use strict'
buh bye 👏

2022-04-19 15:50 UTC, brentlintner commented on main.js
> +import LTSAnalyzer from './ltsanalyzer.js'
Gah, I wish Node wasn't explicit with .js in modules when using ES Modules.

I was wondering if you had too, TL;DR only with experimental flags bleh:

https://stackoverflow.com/questions/64242186/node-cant-find-modules-without-js-extension https://nodejs.org/dist/latest-v14.x/docs/api/esm.html#esm_resolution_algorithm

One day... lol.

2022-04-19 15:50 UTC, brentlintner commented on sqlzconnection.js
> +    for (let i = zero ? 0 : 1; i < keys.length; i++) {
nit: be easier to read as a forEach, or an async await (ex: `await Lodash.map(...) -> Array<Promise<queryResult>>` syntax)

2022-04-19 16:47 UTC, catalinzpop commented on sqlzconnection.js
> +  try {
Good point

2022-04-19 16:47 UTC, catalinzpop commented on README.md
> + This will do the same thing as the above example except it will not create json files but will instead update the stress_level collumn in the ways table of your postgress routing database. This opti
Yeah I can't spell apparently

2022-04-19 16:47 UTC, catalinzpop commented on README.md
> + Additionally it requires the WAYS_TABLE_NAME, STRESS_LEVEL_COLUMN_NAME and OSM_ID_COLUMN_NAME in order to target the part of the DB that you would like to update.
Removed

2022-04-19 16:48 UTC, catalinzpop commented on loadmodel.js
> -'use strict'
🙅‍♂️

2022-04-19 16:53 UTC, catalinzpop commented on stressmodel.js
> +function getLanes (way) {
Will go and fix them

2022-04-20 16:17 UTC, merged