Added sanity test to compare any rule changes made by the current model
zeitspace/stressmodel pull request #48
Opened 2022-11-01 20:42 UTC by catalinzpop

Added a sanity test to check changes made by the current model. Easiest way to test this is: 
-Change one of the rules by either removing some tag assignments or removing the rule completely in stressmodel.js
-Run './bin/generate-base-test-file' (if this fails with a permission error run 'chmod +x bin/generate-base-test-file')
-Undo the changes you've made to the stressmodel.js
-Run './bin/test'
-Observe the rule counts and the differences to the rules
-Hit 'y' on the prompt asking to update the base test file in order to update it

2022-11-01 20:44 UTC, catalinzpop commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create sanity tests for the stress model output](https://trello.com/c/LAUYdNfq/543-create-sanity-tests-for-the-stress-model-output)

2022-11-02 16:23 UTC, JacksonZeitspace approved these changes

2022-11-03 01:18 UTC, brentlintner reviewed
I noticed `test/baseRules.json` is a single line. So it will effectively be changed every time.

This means the repository history and size will grow indefinitely by 2.4MB every time we do.

Say we update it 4 times every week, then we will hit a non ideal [1GB](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#repository-size-limits) in ~2 years? 🤔 😳

2022-11-03 01:24 UTC, brentlintner commented on package.json
> +    "json-diff": "https://github.com/catalinzpop/json-diff",
For consistency we should probably fork this under Zeitspace instead.

2022-11-03 01:34 UTC, brentlintner requested changes
This is awesome. I have a few adjacent concerns though. Let me know what you think? 🤷 😄 

Side note: about the nitpicks during demo (lol), while it would be cool to see correct numerical sorting, and even colors + more pretty printing... perhaps we should make a Tech Debt item for later? 🤔

2022-11-03 18:42 UTC, catalinzpop commented on ltsanalyzer.js
> +            console.log(`${key.length == 2 ? key + ' ' : key} ${this.LTScolour[ruleLTS[key]]('(LTS ' + (ruleLTS[key].toString().length > 1 ? ruleLTS[key] : ' ' + ruleLTS[key]) + ')')} = ${counts[key]
Sorry for this

2022-11-03 19:22 UTC, brentlintner commented on stressmodel.json
> -            "present": true
Should put this back?

2022-11-03 19:22 UTC, brentlintner commented on package.json
> +    "json-diff": "https://github.com/zeitspace/json-diff",
See my double fork comment in slack! 😅

2022-11-03 19:24 UTC, brentlintner commented on ltsanalyzer.js
> +            console.log(`${key.length == 2 ? key + ' ' : key} ${this.LTScolour[ruleLTS[key]]('(LTS ' + (ruleLTS[key].toString().length > 1 ? ruleLTS[key] : ' ' + ruleLTS[key]) + ')')} = ${counts[key]
![noooo](https://user-images.githubusercontent.com/93340/199815510-5ebe6cde-48f1-491e-8131-d73c782ced34.gif)

2022-11-03 22:16 UTC, catalinzpop commented on stressmodel.json
> -            "present": true
Yes I did sorry bout that

2022-11-03 22:29 UTC, brentlintner approved these changes
LGTM. 🦅

2022-11-07 16:59 UTC, merged