Added linting and fixed files
zeitspace/stressmodel pull request #56
Opened 2022-11-15 18:35 UTC by JacksonZeitspace

2022-11-15 19:48 UTC, brentlintner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add a JS linter to the Stressmodel](https://trello.com/c/hrAG41zg/831-add-a-js-linter-to-the-stressmodel)

2022-11-15 20:44 UTC, brentlintner requested changes

2022-11-15 20:44 UTC, brentlintner commented on .eslintrc.json
> +}
Readme docs on how to lint?

2022-11-15 20:44 UTC, brentlintner commented on db.js
> +import readline from "readline";
Dig the double quotes, personally. 🥳

2022-11-15 20:44 UTC, brentlintner commented on main.js
> +    value: "DB_USER",
Please can we not have trailing commas required lol. 🙏

2022-11-15 20:44 UTC, brentlintner commented on package.json
> +    "jshint": "^2.13.5",
Is JSHint required as well?

2022-11-15 20:44 UTC, brentlintner commented
![Screen Shot 2022-11-15 at 15 35 36](https://user-images.githubusercontent.com/93340/202020114-8c17b4e0-b97b-490e-9e8e-d1ae6ced3ee9.png)
 
<hr />

![neurotic-sadge](https://user-images.githubusercontent.com/93340/202020509-d629bfbd-3b17-4017-8ec1-88849c96cba7.gif)

2022-11-15 20:46 UTC, brentlintner commented
LGTM in general, aside from a few nitpicks and opinionated pleadings. 😄

2022-11-15 20:50 UTC, JacksonZeitspace commented on package.json
> +    "jshint": "^2.13.5",
oops, no. I used it at one point

2022-11-15 20:50 UTC, JacksonZeitspace commented on main.js
> +    value: "DB_USER",
Yea I'll change it

2022-11-15 21:00 UTC, JacksonZeitspace commented on .eslintrc.json
> +}
Added

2022-11-16 20:48 UTC, brentlintner approved these changes
![danke](https://user-images.githubusercontent.com/93340/202290944-235371ce-d632-42b8-aeca-6869724cdf92.gif)

2022-11-17 13:52 UTC, merged