Added the ability to accept command line db args
zeitspace/stressmodel pull request #6
Opened 2022-04-26 19:56 UTC by catalinzpop

2022-04-27 14:11 UTC, zeitspacetyler requested changes

2022-04-27 14:11 UTC, zeitspacetyler commented on sqlzconnection.js
> +      const null_ways_res = await sequelize.query(`SELECT count(*) FROM ${ways_table_name} WHERE ${stress_level_column_name} IS NULL`, { type: QueryTypes.SELECT });
Same as above comment

2022-04-27 20:52 UTC, peterspenler requested changes

2022-04-27 20:52 UTC, peterspenler commented on sqlzconnection.js
> +        throw `The --db_uri or the --db_user --db_host and --pg_user arguments need to be set in the command line OR
The arguments should be updated to use hyphens in this error message as well

2022-04-28 17:23 UTC, catalinzpop commented on sqlzconnection.js
> +        WHERE ${osm_id_column_name}
I updated the query to be built using pg-format but I still used sequilize since pg did not work for me

2022-04-28 17:23 UTC, catalinzpop commented on README.md
> + * --db_uri                   is used by the previous flag as a database URI. This replaces all the other db_* flags.
Fixed them

2022-04-28 17:23 UTC, catalinzpop commented on sqlzconnection.js
> +        throw `The --db_uri or the --db_user --db_host and --pg_user arguments need to be set in the command line OR
must've missed these, they are now updated

2022-04-28 19:14 UTC, zeitspacetyler requested changes

2022-04-28 19:20 UTC, AmyColf requested changes

2022-04-28 19:20 UTC, AmyColf commented on sqlzconnection.js
> +        comma_delimited_way_ids
This one worries me a bit, do you know how long this list of way IDs can get? If you put a couple hundred in here for example, that could cause problems for the DB. I don't think postgres limits this itself and will happily parse massive queries.

2022-04-28 19:20 UTC, AmyColf commented on options.js
> +    console.log('  --db-host=DB-HOST                The name of the host of the postgress database connection.')
Btw for future reference: This is an amazing library for taking care of a lot of this kind of boilerplate. https://www.npmjs.com/package/commander

2022-05-02 20:57 UTC, zeitspacetyler approved these changes

2022-05-03 15:59 UTC, brentlintner commented
@catalinzpop noticed a small CLI issue where exit code is 1 if you type `node main.js -h`.

If you have time and want to, quick hack in `main.js` (line 10):

```javascript
.....
} else {
  const printedHelp = args[2] == "-h" || args[2] == '--help'
  const errorMessage = printedHelp ? undefined :
    'An error occurred while parsing the command line.'
  runComplete(errorMessage)
}
```

2022-05-04 15:50 UTC, peterspenler requested changes

2022-05-04 15:50 UTC, peterspenler commented on pgconnection.js
> +    console.error('Database connection error:', error);
The program should exit with a non-zero code if it fails to connect to the database, otherwise it could hang a CI script

2022-05-04 16:22 UTC, catalinzpop commented on pgconnection.js
> +    console.error('Database connection error:', error);
I added a return value and a promise .then to check for it. Should return an error now if it fails

2022-05-04 19:12 UTC, peterspenler approved these changes
LGTM

2022-05-04 19:25 UTC, catalinzpop commented on options.js
> +    console.log('  --db-host=DB-HOST                The name of the host of the postgress database connection.')
Working on this on a different branch. Thanks for the suggestion

2022-05-04 19:25 UTC, merged