Added the ability to update an osm file with 'lts' tags and write it …
zeitspace/stressmodel pull request #66
Opened 2023-03-15 18:23 UTC by catalinzpop

…back to the original or to a new file

To test it run `./bin/add-lts-tags-to-osm-file` in the stressmodel repo. This updates your .osm file in your cycling_data repo. You can run it multiple times and it should only add one lts tag.

2023-03-15 18:56 UTC, catalinzpop commented
![](https://github.trello.services/images/mini-trello-icon.png) [Put LTS data in OSM file](https://trello.com/c/3dDykooV/1152-put-lts-data-in-osm-file)

2023-03-15 20:16 UTC, JacksonZeitspace approved these changes

2023-03-17 19:53 UTC, brentlintner requested changes
Left some thoughts on keeping repo osm generic and extraneous deps.

Also the last two commits seem like fixup commits and could be rebased into previous ones, if anything.

Runs for me though! 🦅

2023-03-17 19:53 UTC, brentlintner commented on bin/update-osm-file-with-lts-tags
> +echo "../cycling_data/data/waterloo-region.osm has been updated"
Since this is OSS and technically an OSM agnostic library, I think it makes sense to document this in the README as a generic example (ex: "Adding LTS levels directly to an OSM file"), instead of having these scripts.

Then we can create scripts as need be when tying together OpenMapTiles+GoBikeRouter CI builds for specific regions.

2023-03-17 19:53 UTC, brentlintner commented on ltsanalyzer.js
> +          w.tag = [ ...w.tag, { "$": { "k": "lts", "v": `${this.ways[w.$.id].level}` } }];
Be more readable to have various parts of `updateOsmWithLTS()` broken down into more expressive methods where possible. 😄

2023-03-17 19:53 UTC, brentlintner commented on package.json
>      "pg": "^8.7.3",
Is this package used?

2023-03-17 19:53 UTC, brentlintner commented on package.json
> +    "through2": "^4.0.2",
Same here, is this used in final code?

2023-03-17 19:53 UTC, brentlintner commented on package.json
> +    "xml-stream": "^0.4.5",
Same here.

2023-03-21 21:19 UTC, brentlintner approved these changes
🦅

2023-03-21 21:22 UTC, merged